url: https://demon-prin.github.io
baseurl: /

# Site settings
title: DEMON PRIN22
email: atzori@unica.it
description: "DEMON is a PRIN22 research project that aims to characterize and detect the manipulation of online information combining both natural language processing (NLP) and social network analysis techniques."

# Team names, titles and social links
people:
- name: Prof. Maurizio Atzori
  pic: 1
  position: University of Cagliari
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: Prof. Stefano Ceri
  pic: 2
  position: Politecnico di Milano
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

- name: Dr. Francesco Pierri
  pic: 3
  position: Politecnico di Milano
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

- name: Prof. Marco Brambilla
  pic: 5
  position: Politecnico di Milano

- name: Prof. Alessandro Campi
  pic: 5b
  position: Politecnico di Milano

- name: Prof. Cecilia Di Ruberto
  pic: 6
  position: University of Cagliari
  
- name: Dr. Manuela Sanguinetti
  pic: 7
  position: University of Cagliari

- name: Dr. Andrea Loddo
  pic: 8
  position: University of Cagliari
  
- name: Luca Zedda
  pic: 9
  position: University of Cagliari

- name: Alessandra Perniciano
  pic: 10
  position: University of Cagliari

- name: Luca Faccin
  pic: 11
  position: University of Cagliari
  
- name: Davide Antonio Mura
  pic: 13
  position: University of Cagliari
  
- name: Marco Usai
  pic: 12
  position: University of Cagliari



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: DMI, Via Ospedale 72, 09124 Cagliari (Italy)
  - line: DEIB, Via Ponzio 34/5, 20133 Milano (Italy)

# Build settings
markdown: kramdown
permalink: pretty
